### ISSUE TITLE
DVP Constellation Summary and Score

### ISSUE THREAD

**Issue by karl-project-review** [cphilippi/dvp-u3-constellations#1]
### Criteria 1: Matplotlib and CSV
* _Score Level:_ 4/4 (Exceeds Expectations) 
* _Comments:_ You correctly imported all the necessary libraries.
### Criteria 2: Implementation of 2D Visualization
* _Score Level:_ 4/4 (Exceeds Expectations) 
* _Comments:_ You correctly created a 2D scatterplot of the constellation and included an appropriate title. Well done!
### Criteria 3: Implementation of 3D Visualization
* _Score Level:_ 4/4 (Exceeds Expectations) 
* _Comments:_ You created a rotatable 3D plot of the constellation with an appropriate title. Nice work!
### Overall Score: 12/12 (Exceeds Expectations)
Great job! You created both of the required plots and included fitting titles for them. To take your visualizations to the next level, consider playing with the marker types and colors to find a combination that you feel best represents the constellation. Again, great job!

**Comment by cphilippi** [comment]
Thanks!
